name: Vulnerability Report
description: Report a potential software vulnerability
title: "[Vulnerability]: "
body:
  - type: textarea 
    id: summary
    attributes:
      label: General Summary
      description: Please provide a general summary of the problem
      placeholder: e.g. "An unsafe deserialization vulnerability allows any unauthenticated user to execute arbitrary code on the server."
    validations:
      required: true
  - type: textarea 
    id: component
    attributes:
      label: Effected Component(s)
      description: List the components effected by this vulnerability
    validations:
      required: true
  - type: textarea 
    id: impact 
    attributes:
      label: Impact of Vulnerability
      description: Describe the scope of the vulnerability's impact
    validations:
      required: true
  - type: textarea
    id: remediation
    attributes:
      label: Possible Remediation
      description: Propose a remediation suggestion if you have one.
      validations:
      required: false
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Explain how to reproduce the problem
      placeholder: e.g. "1. The first step to reproduce this error is to access the members area..."
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Detailed Description
      description: Please provide a more detailed description
    validations:
      required: false 
